# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: bley.spec

# add or remove files that should be synced
files_to_sync:
    - bley.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: bley
# downstream (Fedora) RPM package name
downstream_package_name: bley

upstream_tag_template: bley/{version}
