branches:
  except:
    - page-source
    - gh-pages

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "2.7"
env:
  # Debian Stretch
  - TWISTED_VERSION=16.6.0
  # Debian Buster, Debian Sid
  - TWISTED_VERSION=18.9.0
  # latest upstream
  - TWISTED_VERSION=20.3.0
# command to install dependencies
install:
  - pip install tox-travis
  - mkdir -p $HOME/bin/
  - wget -O $HOME/bin/my_virtualenv https://raw.github.com/evgeni/my_virtualenv/master/my_virtualenv
  - chmod +x $HOME/bin/my_virtualenv
# command to run tests
script:
  - PATH=$HOME/bin:$PATH tox
  - python setup.py install --root=/tmp/bley
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
