.TH BLEYGRAPH "1" "July 2010" "bleygraph 0.2" "bley"
.SH NAME
bleygraph \- stats plotter for bley
.SH SYNOPSIS
.B bleygraph
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-d\fR DESTDIR, \fB\-\-destdir\fR=\fIDESTDIR\fR
write to DESTDIR
.TP
\fB\-c\fR CONFFILE, \fB\-\-config\fR=\fICONFFILE\fR
load configuration from CONFFILE
.TP
\fB\-q\fR, \fB\-\-quiet\fR
be quiet (no output)
