.TH BLEY "1" "May 2014" "bley 2.0.0-beta.1" "bley"
.SH NAME
bley \- intelligent greylisting daemon for Postfix
.SH SYNOPSIS
.B bley
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-p\fR \fIPID_FILE\fR, \fB\-\-pidfile\fR=\fIPID_FILE\fR
use PID_FILE for storing the PID
.TP
\fB\-c\fR \fICONFFILE\fR, \fB\-\-config\fR=\fICONFFILE\fR
load configuration from CONFFILE
.TP
\fB\-v\fR, \fB\-\-verbose\fR
use verbose output
.TP
\fB\-d\fR, \fB\-\-debug\fR
don't daemonize the process and log to stdout
\fB\-f\fR, \fB\-\-foreground\fR
don't daemonize the process
