name: CI

on: [push, pull_request]

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        twisted:
          - "16.6.0"
          - "18.9.0"
          - "20.3.0"
          - "22.4.0"
          - "22.10.0"
        exclude:
          - python: "3.6"
            twisted: "22.10.0"
          - python: "3.11"
            twisted: "16.6.0"
          - python: "3.11"
            twisted: "18.9.0"
          - python: "3.11"
            twisted: "20.3.0"
    env:
      PYTHON: ${{ matrix.python }}
      TWISTED_VERSION: ${{ matrix.twisted }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install tox tox-gh-actions
      - name: Run tests
        run: tox
