name: CI

on:
  push:
    branches:
      - devel
    tags:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        twisted:
          - "22.4.0"
          - "23.10.0"
        include:
          - python: "3.6"
            twisted: "16.6.0"
          - python: "3.7"
            twisted: "18.9.0"
          - python: "3.9"
            twisted: "20.3.0"
    env:
      PYTHON: ${{ matrix.python }}
      TWISTED_VERSION: ${{ matrix.twisted }}
      BLEY_TEST_ALLOW_NETWORK: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install my_virtualenv
        run: |
          sudo curl --location --create-dirs --output /usr/local/bin/my_virtualenv https://raw.githubusercontent.com/evgeni/my_virtualenv/devel/my_virtualenv
          sudo chmod +x /usr/local/bin/*
      - name: Install dependencies
        run: pip install tox tox-gh-actions
      - name: Run tests
        run: tox
